### ISSUE TITLE
Bow Spot Bracket

### ISSUE THREAD

**Issue by vangalder** [vangalder/Harvest-Moon#121]

**Comment by TheAmazingWolzini** [comment]
Scheduled 4/13

**Comment by TheAmazingWolzini** [comment]
[Bow Spot Drawing.pdf](https://github.com/vangalder/Harvest-Moon/files/8485459/Bow.Spot.Drawing.pdf)

**Comment by TheAmazingWolzini** [comment]
with dimensions
[Bow Spot Drawing.pdf](https://github.com/vangalder/Harvest-Moon/files/8485505/Bow.Spot.Drawing.pdf)

**Comment by vangalder** [comment]
will take print-out to machinist mid-week next week (~4/20) ... oh great, he'll be lit 💨

**Comment by TheAmazingWolzini** [comment]
Waiting on part from machinist
