### ISSUE TITLE
source tiles for under bladder

### ISSUE THREAD

**Issue by TheAmazingWolzini** [vangalder/Harvest-Moon#125]
https://www.amazon.com/ProSource-fs-1908-pzzl-Puzzle-Exercise-Interlocking/dp/B07YN1W5W3/ref=sr_1_6?crid=185DJF2TY3Y73&keywords=puzzle%2Bpiece%2Bmats%2Bfor%2Bfloors&qid=1649897817&sprefix=puzzle%2Bpiece%2Bmat%2Caps%2C113&sr=8-6&th=1

**Comment by vangalder** [comment]
tiles are ordered; ETA 4/18 at Mike's
