### ISSUE TITLE
re-install winch handle holder

### ISSUE THREAD

**Issue by vangalder** [vangalder/Harvest-Moon#61]

**Comment by TheAmazingWolzini** [comment]
Do we want to make screw holes for this, or source those folding handles you can leave in like Uma uses?

**Comment by vangalder** [comment]
link for those?

**Comment by TheAmazingWolzini** [comment]
https://easysea.org/ looks like still wait list, we can decide where to mount that on 4200 day

**Comment by vangalder** [comment]
I've purchased one of those EasySea winch handles
