### ISSUE TITLE
velcro on bottom of water bladder 

### ISSUE THREAD

**Issue by vangalder** [vangalder/Harvest-Moon#81]

**Comment by vangalder** [comment]
Let's look at this together and discuss pros and cons for each option.  

[https://www.mcmaster.com/hook-and-loop-fasteners/](https://www.mcmaster.com/hook-and-loop-fasteners/)

These look burly as fuck:
[https://www.mcmaster.com/94915K751/](https://www.mcmaster.com/94915K751/)

**Comment by TheAmazingWolzini** [comment]
doing other plan, resolved
