### ISSUE TITLE
glue bushings into solar panel mounts

### ISSUE THREAD

**Issue by vangalder** [vangalder/Harvest-Moon#94]

**Comment by TheAmazingWolzini** [comment]
So are we just cutting the existing ones in half and gluing them with plastic epoxy? I can get on that if so

**Comment by vangalder** [comment]
Trying to find spares from the manufacturer

**Comment by TheAmazingWolzini** [comment]
Scheduled 4/22

**Comment by vangalder** [comment]
still no word from the manufacturer about replacement bushings; can we find more of that hose material that you used on the one mount, but slightly thicker?

**Comment by TheAmazingWolzini** [comment]
I dont think thicker is an option on that stuff.

**Comment by vangalder** [comment]
I have some neoprene on the way from McMaster that looks to solve this issue as well as serve as padding for the lazarette

**Comment by TheAmazingWolzini** [comment]
Fantastic

**Comment by vangalder** [comment]
find out from Mike what contact cement I should use to augment the adhesive already on the neoprene strip
